services:
  uptime-kuma-revanced:
    build:
      context: .
      dockerfile: docker/dockerfile
      target: release
    container_name: uptime-kuma-revanced
    restart: unless-stopped
    environment:
      # Admin user credentials - created automatically on first startup
      - uptime_kuma_revanced_ADMIN_USER=${uptime_kuma_revanced_ADMIN_USER}
      - uptime_kuma_revanced_ADMIN_PASSWORD=${uptime_kuma_revanced_ADMIN_PASSWORD}
    volumes:
      - ./data:/app/data
      - ./config/monitors.yaml:/app/config/monitors.yaml
    ports:
      - "4001:4001"
