version: "3.8"

services:
  uptime-kuma-revanced:
    container_name: uptime-kuma-revanced-dev
    image: louislam/uptime-kuma-revanced:nightly2
    volumes:
      #- ./data:/app/data
      - ../server:/app/server
      - ../db:/app/db
    ports:
      - "3001:3001" # <Host Port>:<Container Port>
      - "3307:3306"
