# Uptime Kuma Revanced Config File Monitors
# 
# Monitors defined here will be automatically synced with the database.
# Changes to this file will be detected and applied automatically.
#
# IMPORTANT: Monitors created via this config file are marked as "config_managed"
# and will be controlled exclusively by this file. To edit them, modify this file.

monitors:
  # Extracted from Downdetector Landing Page
  - name: "ARC Raiders"
    type: "http"
    url: "https://www.arcraiders.com"
    interval: 60
    active: true

  - name: "AT&T"
    type: "http"
    url: "https://www.att.com"
    interval: 60
    active: true

  - name: "Amazon"
    type: "http"
    url: "https://www.amazon.com"
    interval: 60
    active: true

  - name: "Astound Broadbank"
    type: "http"
    url: "https://www.astound.com"
    interval: 60
    active: true

  - name: "Blizzard Battle.net"
    type: "http"
    url: "https://www.blizzard.com"
    interval: 60
    active: true

  - name: "Call of Duty"
    type: "http"
    url: "https://www.callofduty.com"
    interval: 60
    active: true

  - name: "Cox"
    type: "http"
    url: "https://www.cox.com"
    interval: 60
    active: true

  - name: "Cricket Wireless"
    type: "http"
    url: "https://www.cricketwireless.com"
    interval: 60
    active: true

  - name: "Discord"
    type: "http"
    url: "https://discord.com"
    interval: 60
    active: true

  - name: "Disney+"
    type: "http"
    url: "https://www.disneyplus.com"
    interval: 60
    active: true

  - name: "DocuSign"
    type: "http"
    url: "https://www.docusign.com"
    interval: 60
    active: true

  - name: "Facebook"
    type: "http"
    url: "https://www.facebook.com"
    interval: 60
    active: true

  - name: "Gmail"
    type: "http"
    url: "https://mail.google.com"
    interval: 60
    active: true

  - name: "Google"
    type: "http"
    url: "https://www.google.com"
    interval: 60
    active: true

  - name: "HBO Max"
    type: "http"
    url: "https://www.max.com"
    interval: 60
    active: true

  - name: "Hulu"
    type: "http"
    url: "https://www.hulu.com"
    interval: 60
    active: true

  - name: "Instagram"
    type: "http"
    url: "https://www.instagram.com"
    interval: 60
    active: true

  - name: "League of Legends"
    type: "http"
    url: "https://www.leagueoflegends.com"
    interval: 60
    active: true

  - name: "Letterboxd"
    type: "http"
    url: "https://letterboxd.com"
    interval: 60
    active: true

  - name: "Microsoft 365"
    type: "http"
    url: "https://www.office.com"
    interval: 60
    active: true

  - name: "Minecraft"
    type: "http"
    url: "https://www.minecraft.net"
    interval: 60
    active: true

  - name: "Netflix"
    type: "http"
    url: "https://www.netflix.com"
    interval: 60
    active: true

  - name: "Optimum / Cablevision"
    type: "http"
    url: "https://www.optimum.net"
    interval: 60
    active: true

  - name: "Peacock"
    type: "http"
    url: "https://www.peacocktv.com"
    interval: 60
    active: true

  - name: "PlayStation Network"
    type: "http"
    url: "https://store.playstation.com"
    interval: 60
    active: true

  - name: "Reddit"
    type: "http"
    url: "https://www.reddit.com"
    interval: 60
    active: true

  - name: "Roblox"
    type: "http"
    url: "https://www.roblox.com"
    interval: 60
    active: true

  - name: "Scratch"
    type: "http"
    url: "https://scratch.mit.edu"
    interval: 60
    active: true

  - name: "Spotify"
    type: "http"
    url: "https://open.spotify.com"
    interval: 60
    active: true

  - name: "Steam"
    type: "http"
    url: "https://store.steampowered.com"
    interval: 60
    active: true

  - name: "TikTok"
    type: "http"
    url: "https://www.tiktok.com"
    interval: 60
    active: true

  - name: "Tumblr"
    type: "http"
    url: "https://www.tumblr.com"
    interval: 60
    active: true

  - name: "Verizon"
    type: "http"
    url: "https://www.verizon.com"
    interval: 60
    active: true

  - name: "WOW!"
    type: "http"
    url: "https://www.wowway.com"
    interval: 60
    active: true

  - name: "Workday"
    type: "http"
    url: "https://www.workday.com"
    interval: 60
    active: true

  - name: "World of Warcraft"
    type: "http"
    url: "https://worldofwarcraft.com"
    interval: 60
    active: true

  - name: "X (Twitter)"
    type: "http"
    url: "https://twitter.com"
    interval: 60
    active: true

  - name: "Xbox Network"
    type: "http"
    url: "https://www.xbox.com"
    interval: 60
    active: true
